version: '3.8'

networks:
  default:
    driver: bridge   
    name: php-net

services:
  nginx:
    image: nginx:1.25.4
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - mariadb
      - php-fpm
    volumes:
      - ./local-conf/nginx/default.conf:/etc/nginx/conf.d/default.conf # Mount Nginx config
      - ./local-volumes/nginx/www:/var/www  # Mount your application code
      - ./local-volumes/nginx/logs:/var/log/nginx  # Mount Nginx logs     
  

  php-fpm:
    build:
      context: .
      dockerfile: ./Dockerfile-dev
    container_name: php-fpm
    image: visiogate-php-fpm
    volumes:
      - ./local-volumes/nginx/www:/var/www
      - ./local-conf/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./local-conf/php/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
      - ./local-conf/php/laravel.ini:/usr/local/etc/php/conf.d/local.ini
      - ./local-conf/npm/npm-startup.sh:/var/www/npm-startup.sh
    expose:
      - 9000
      - 9003 #xdebug
    ports:
       - 5173:5173
   

  mariadb:
    image: mariadb:11.1
    container_name: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
      MARIADB_DATABASE: mysql
      MARIADB_USER: root
      MARIADB_PASSWORD: laravel
    ports:
      - "3306:3306"
    volumes:
      - ./local-volumes/mariadb/db:/var/lib/mysql:rw
      #non funziona - ./local-volumes/mariadb/initdb.d:/docker-entrypoint-initdb.d/:ro   

  #npm:  
  #  image: node:lts
  #  working_dir: /var/www/
  #  ports:
  #    - 5173:5173
  #  entrypoint: ["/var/www/npm-startup.sh"]
  #  volumes: 
  #    - ./local-volumes/nginx/www:/var/www
  #    - ./local-conf/npm/npm-startup.sh:/var/www/npm-startup.sh
  